<a href="https://colab.research.google.com/github/MrChristianMoreno/UDEMY/blob/main/UdemyNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos Numpy con su abreviacion "np"
import numpy as np

In [2]:
#Podemos crear arrays de una dimension con la funcion np.array()
array_unidim = np.array([1,2,3,4,5])

# O un array de dos dimensiones
array_bidm = np.array([[1,2,3],
                       [4,5,6]])

# O un array de tres dimensiones

array_tridim = np.array([[[1,2,3],
                          [4,5,6]],
                         [[7,8,9],
                          [10,11,12]]])


In [3]:
#Atributos del array unidimensional (forma, numero de dimensiones, tipos de datos, tamaño y tipo)

array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [4]:
#Atributos del array bidimensional (forma, numero de dimensiones, tipos de datos, tamaño y tipo)

array_bidm.shape, array_bidm.ndim, array_bidm.dtype, array_bidm.size, type(array_bidm)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
#Atributos del array tridimensional (forma, numero de dimensiones, tipos de datos, tamaño y tipo)

array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [6]:
#Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidm)
datos

0  1  2
0  1  2  3
1  4  5  6

In [7]:
#Creamos un array de tamaño 4x3, formando unicamente por unos (1)
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#Creamos un array de tamaño 2x4x3, formando unicamente por ceros (0)
cero = np.zeros((2,4,3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
#Creamos un array de numeros en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0,100,5)
array_1


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [12]:
#Creamos un array de numeros aleatorios enteros comprendidos entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2,5))
array_2

array([[8, 1, 8, 3, 2],
       [9, 8, 9, 2, 9]])

In [14]:
#Creamos un array de numeros aleatorios decimales comprendidos entre 0 y 1, de tamaño(3,5)
array_3 = np.random.random((3,5))
array_3

array([[0.88410016, 0.41665084, 0.81826331, 0.26632317, 0.39882731],
       [0.63844652, 0.8239085 , 0.81847357, 0.52255664, 0.54760998],
       [0.09521138, 0.30238268, 0.93235206, 0.48400137, 0.44376289]])

In [15]:
# Establrecemos la semilla de numeros aleatorios en 27
np.random.seed(27)

#Creamos un array de numeros aleatorios enteros comprendidos entre 0 y 10 de tamaño (3,5)
array_4= np.random.randint(0, 10, (3,5))
array_4


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

In [16]:
# Encontramos los valores unicos del array 4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [17]:
#Extraemos el elemento de indice 1 del array 4
array_4[1]

array([5, 8, 9, 1, 2])

In [18]:
#Extraemos las primeras dos filas del array 4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [19]:
#Extraemos los dos primeros datos de las primeras dos filas del array 4
array_4[:2,:2]

array([[3, 8],
       [5, 8]])

In [23]:
#CReamos dos arrays de tamaño 3x4: uno relleno de numeros aleatorios entre 0 y 10 y otro relleno de unos
array_5 = np.random.randint(0, 10, (3,4))
array_6 = np.ones((3,4))


In [24]:
#invocamos el array 5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [25]:
#invocamos el array 6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
#Sumamos los dos arrays
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [28]:
#Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4,3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
#Intentamos sumar los arrays de 6 y 7
array_6 + array_7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [30]:
#Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4,3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
#Restamos el array 8 y el array 7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#Creamos otros dos arrays de tamaño 3x3 con numeros aleatorios del 1 al 5
array_9 = np.random.randint(1,5,(3,3))
array_10 = np.random.randint(1,5,(3,3))

In [33]:
#invocamos el array 9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [34]:
#invocamos el array 10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [35]:
#multiplicamos los ultimos dos arrays entre si
array_9 * array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [36]:
#Elevamos el array 9 al cuadrado
array_9**2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [37]:
#Buscamos la raiz cuadrada del array 10
np.sqrt(array_10)

array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [38]:
# hallamos el promedio de los valores del array 9
array_9.mean()

np.float64(3.0)

In [39]:
#hallamos el valor maximo de los valores del aaray 9
array_9.max()

np.int64(4)

In [40]:
#hallamos elvalor minimo de los valores del array 9
array_9.min()

np.int64(1)

In [41]:
#cambiamos la forma del array 9 por una de 9x1, y lo almacenamos como array 11
array_11 = array_9.reshape((9,1))

In [42]:
#invocamos el array 11
array_11

array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [43]:
#transponemos el array 11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [44]:
#comparamos el array 9 y el array 10 para saber cuales elementos del array 9 son mayores a los del array 10
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

In [46]:
#veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [48]:
#alguno de los elementos del array 9 es igual su equivalente del array 10
array_9 >= array_10

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [49]:
#buscamos elementos del aaray 9 que son mayores a 2
array_9 > 2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [50]:
#ordenamos de menor a mayor los elementos dentro del array 9
np.sort(array_9)

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])